name: Jest # NB: The name is used in workflow_run

on:
  push:
    branches: [main, beta, chore/*, fix/*, feat/*]
  pull_request:
    branches: [main, beta]

jobs:
  build:
    name: Jest tests

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22.x, 24.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use deps cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install --immutable

      - name: Use tests
        run: yarn test
